@startuml
!theme plain
autonumber
skinparam BackgroundColor #FFFFFF
participant WebView order 1[
    =Android WebView
    ----
    ""via https proxy at https://localhost:8443""
]
participant MitMHTTPSProxy order 2 [
    =MitMHTTPSProxy
    ""localhost:8443""
]
participant HTTPProxy order 3 [
    =HTTPProxy
    ""localhost:8080""
]
participant Gosuslugi order 4 [
    =Gosuslugi
    ""gosuslugi.ru""
]
box "Localhost Communication" #LightBlue
participant WebView
participant MitMHTTPSProxy
participant HTTPProxy
end box
box "External Internet Communication" #indianred
participant Gosuslugi
end box
WebView -> MitMHTTPSProxy : TLS.ClientHello with SNI=localhost
MitMHTTPSProxy -> MitMHTTPSProxy : Extract SNI from TLS.ClientHello.\nGenerate Leaf Certificate for SNI based on self signed Root CA
MitMHTTPSProxy --> WebView : Finish TLS Handshake
WebView -> WebView : Trust Leaf certificate based on predefined Root CA\nTLS Handshake finished
group Layer 1. TLS Encryption
  WebView -> MitMHTTPSProxy : "CONNECT gosuslugi.ru\\r\\n\\r\\n" proxy command
end
MitMHTTPSProxy -> HTTPProxy : "CONNECT gosuslugi.ru\\r\\n\\r\\n"
HTTPProxy --> MitMHTTPSProxy : "200 OK\\r\\n\\r\\n"

group Layer 1. TLS Encryption
  MitMHTTPSProxy -> WebView : "200 OK\\r\\n\\r\\n"
  WebView -> MitMHTTPSProxy : TLS.ClientHello with SNI=gosuslugi.ru
  MitMHTTPSProxy -> MitMHTTPSProxy : Extract SNI from TLS.ClientHello.\nGenerate Leaf Certificate for SNI based on self signed Root CA
  MitMHTTPSProxy --> WebView : Finish TLS Handshake
  WebView -> WebView : Trust Leaf certificate based on predefined Root CA\nTLS Handshake finished

  group Layer 2. TLS Encryption
    WebView -> MitMHTTPSProxy : "GET / HTTP/1.1\\r\\n\\r\\n"
  end
end

MitMHTTPSProxy -> HTTPProxy : "GET / HTTP/1.1\\r\\n\\r\\n"
HTTPProxy -> Gosuslugi : TLS Handshake Initiation via CryptoPro GOST TLS
Gosuslugi -> HTTPProxy : TLS Handshake Finish
group Layer 3. GOST TLS Encryption
  HTTPProxy -> Gosuslugi : "GET / HTTP/1.1\\r\\n\\r\\n"
  Gosuslugi -> HTTPProxy : "200 OK\\r\\n\\r\\n with HTML content"
end

HTTPProxy -> MitMHTTPSProxy : "200 OK\\r\\n\\r\\n with HTML content"

group Layer 1. TLS Encryption
  group Layer 2. TLS Encryption
    MitMHTTPSProxy -> WebView : "200 OK\\r\\n\\r\\n with HTML content"
  end
end
@enduml
